islandjoinmessage:
  join: "§a Du wurdest zu deiner Insel teleportiert"
defaultworldbordersize:
  size: 75
oneblockblocks:
  Anfänger:
    - STONE
    - DIRT
    - COBBLESTONE
  Oberwelt:
    - IRON_ORE
    - COAL_ORE
    - GRANITE
  Eis:
    - DIAMOND_ORE
    - GOLD_ORE
    - REDSTONE_ORE
