islandjoinmessage:
  join: "§a Du wurdest zu deiner Insel teleportiert"
  notowned: "§cDeine Insel Wurde Erstellt"
defaultworldbordersize:
  size: 200
InselPadding:
  value: 400
oneblockblocks:
  1:
    - STONE
    - DIRT
    - COBBLESTONE
  2:
    - IRON_ORE
    - COAL_ORE
    - GRANITE
  3:
    - DIAMOND_ORE
    - GOLD_ORE
    - REDSTONE_ORE