# Nachricht, die angezeigt wird, wenn der Spieler zu seiner Insel teleportiert wird
islandjoinmessage:
  join: "§a Du wurdest zu deiner Insel teleportiert"
  notowned: "§aDeine Insel Wurde Erstellt"

# Standardgröße der Weltgrenze
defaultworldbordersize:
  size: 200

# Der Pufferabstand für Inseln
InselPadding:
  value: 400

# Definiert die Blöcke, die bei einem OneBlock nach bestimmten Insel-Leveln erscheinen
oneblockblocks:
  '1':
    - STONE
    - DIRT
    - GRASS_BLOCK
    - COBBLESTONE
  '2':
    - OAK_LOG
    - SPRUCE_LOG
    - BIRCH_LOG
    - JUNGLE_LOG
    - ACACIA_LOG
    - DARK_OAK_LOG
    - OAK_LEAVES
    - BIRCH_LEAVES
    - JUNGLE_LEAVES
    - ACACIA_LEAVES
    - DARK_OAK_LEAVES
    - DIRT
    - GRASS_BLOCK
    - STONE
    - COBBLESTONE
    - COARSE_DIRT
    - PODZOL
  '3':
    - IRON_ORE
    - COAL_ORE
    - COPPER_ORE
    - GRANITE
    - ANDESITE
  '4':
    - DIAMOND_ORE
    - GOLD_ORE
    - REDSTONE_ORE

# Loot-Kisten-Optionen und deren Inhalte
available-chests:
  - "basic_chest"
  - "advanced_chest"

# Hier definierst du die Loot-Inhalte für jede Kiste
chests:
  basic_chest:
    - "STONE:5"
    - "IRON_ORE:3"
    - "GOLD_ORE:2"
    - "COAL_ORE:8"
  advanced_chest:
    - "DIAMOND_ORE:1"
    - "EMERALD_ORE:1"
    - "GOLD_BLOCK:3"
    - "IRON_BLOCK:5"

# Andere Konfigurationsoptionen
value: 400
