islandjoinmessage:
  join: "§a Du wurdest zu deiner Insel teleportiert"
  notowned: "§aDeine Insel wurde Erstellt"
  create: "§a Insel wird erstellt bitte habe Geduld"
defaultworldbordersize:
  size: 200
InselPadding:
  value: 400
DeniedMessage: "§aDu wurdest von dieser Insel gebannt! Bitte den Besitzer dich zu entbannen wenn du die Insel besuchen möchtest."
denymessagealreadydenied: "§a Dieser Spieler ist bereits gebannt."
addmessagealreadyadded: "§cDieser Spieler wurde bereits eingeladen"
trustmessage: "§aDu hast %player% auf deine Insel eingeladen"
unbanmessage: "§a Du hast %player% von deiner Insel entbannt"
banmessage: "§a Du hast %player% von deiner Insel gebannt"
notbannedmessage: "§aDer Spieler ist nicht gebannt!"
removemessage: "§a Du hast %player% von deiner Insel entfernt"
removeplayernotinlist: "§Der Spieler ist nicht auf deiner Insel hinzugefügt"
rebirthinventoryfull: "§cDein Inventar ist voll bitte leere es um zu den Rebirth durchzuführen"
rebirthhigherlevel: "§cDein Level ist nicht hoch genug um den rebirth durchzuführen. Du brauchst das level %level% um zu rebirthen "
RebirthLevel: 12
Server: "§6§lBlockhive >> "
oneblockblocks:
  '1': # Natur & Erde
    - DIRT
    - GRASS_BLOCK
    - COARSE_DIRT
    - PODZOL
    - CLAY

  '2': # Holz & Bäume
    - OAK_LOG
    - SPRUCE_LOG
    - BIRCH_LOG
    - JUNGLE_LOG
    - ACACIA_LOG
    - DARK_OAK_LOG
    - OAK_WOOD
    - SPRUCE_WOOD
    - BIRCH_WOOD
    - STRIPPED_OAK_LOG
    - STRIPPED_SPRUCE_LOG
    - STRIPPED_BIRCH_LOG
    - STRIPPED_JUNGLE_LOG
    - OAK_LEAVES
    - SPRUCE_LEAVES
    - BIRCH_LEAVES
    - JUNGLE_LEAVES
    - ACACIA_LEAVES
    - DARK_OAK_LEAVES
    - MOSS_BLOCK
    - MOSSY_COBBLESTONE

  '3': # Stein & Gestein
    - STONE
    - COBBLESTONE
    - ANDESITE
    - DIORITE
    - GRANITE
    - TUFF
    - STONE_BRICKS
    - CRACKED_STONE_BRICKS

  '4': # Unterirdische Materialien
    - COAL_BLOCK
    - IRON_BLOCK
    - COPPER_BLOCK
    - DEEPSLATE
    - COBBLED_DEEPSLATE
    - POLISHED_DEEPSLATE
    - DEEPSLATE_BRICKS
    - DEEPSLATE_TILES

  '5': # Edelmetalle & Seltenesss
    - GOLD_BLOCK
    - REDSTONE_BLOCK
    - LAPIS_BLOCK
    - EMERALD_BLOCK
    - DIAMOND_BLOCK
    - OBSIDIAN

  '6': # Nether-Biomaterialien
    - NETHERRACK
    - SOUL_SAND
    - SOUL_SOIL
    - BASALT
    - POLISHED_BASALT
    - BLACKSTONE
    - POLISHED_BLACKSTONE
    - NETHER_BRICKS
    - RED_NETHER_BRICKS

  '7': # Nether-Wald
    - CRIMSON_NYLIUM
    - WARPED_NYLIUM
    - CRIMSON_STEM
    - WARPED_STEM
    - STRIPPED_CRIMSON_STEM
    - STRIPPED_WARPED_STEM
    - CRIMSON_HYPHAE
    - WARPED_HYPHAE
    - SHROOMLIGHT

  '8': # End-Stufe
    - END_STONE
    - PURPUR_BLOCK
    - PURPUR_PILLAR
    - END_STONE_BRICKS
    - OBSIDIAN
    - CHISELED_PURPUR_BLOCK

  '9': # Magie & Reichtum
    - QUARTZ_BLOCK
    - CHISELED_QUARTZ_BLOCK
    - SMOOTH_QUARTZ
    - HONEY_BLOCK
    - SLIME_BLOCK
    - GILDED_BLACKSTONE
    - ANCIENT_DEBRIS
    - NETHERITE_BLOCK

  '10': # Dekor & Luxus
    - GLOWSTONE
    - SEA_LANTERN
    - PRISMARINE
    - PRISMARINE_BRICKS
    - DARK_PRISMARINE
    - BEACON
    - LODESTONE