name: oneblockplugin
version: '1.0'
main: de.Main.OneBlock.Main
api-version: '1.21'

commands:
  ob:
    description: OneBlock Command
    usage: /ob join | /ob delete | ...
    permission: oneblock.use
    permission-message: §cDu hast keine Berechtigung diesen Befehl zu verwenden.
  obgui:
    description: Öffnet das OneBlock GUI
    usage: /obgui
  scoreboardreload:
    description: Reloads the scoreboard config
    usage: /scoreboardreload
    permission: oneblock.gui
  globaltrash:
    description: Öffnet das OneBlock GUI
    usage: /globaltrash
    permission: oneblock.gui
  kristallshop:
    description: Öffnet den Kristall-Shop
    usage: /kristallshop
  pickaxeshop:
    description: Öffnet den Spitzhacken-Shop
    usage: /pickaxeshop

permissions:
  oneblock.use:
    description: Basisberechtigung für /ob
    default: true

  oneblock.admin:
    description: Vollzugriff auf alle OneBlock-Befehle
    default: op

  oneblock.gui:
    description: Öffnet das OneBlock GUI
    default: true

  oneblock.join: {}
  oneblock.delete: {}
  oneblock.visit: {}
  oneblock.rebirth: {}
  oneblock.trust: {}
  oneblock.accept: {}
  oneblock.deny: {}
  oneblock.unban: {}
  oneblock.remove: {}
  oneblock.leave: {}
  oneblock.decline: {}
