name: OneBlockPlugin  # Dies ist gültig
version: '1.0'
main: de.Main.OneBlock.Main
api-version: '1.21'
commands:
  ob:
    description: OneBlock Command
    usage: /ob join
  obgui:
    description: Öffnet das OneBlock GUI
    usage: /obgui

